### ISSUE TITLE
Bad results on MidAir data

### ISSUE THREAD

**Issue by dimaxano** [michael-fonder/M4Depth#4]
Hi!

I downloaded part of MidAir data (Kite_training/sunny/00-19), made protobuffs from them.
At the testing I get very strange results: predicted depth maps are completely gray or with horizontal \ vertical lines pattern ([examples](https://drive.google.com/drive/folders/1EC07S3daBNYVIyK8i0Cn-uI9338GYQf6?usp=sharing))

Here is error statistics, which is also not satisfying:
```
Average batch processing time : 35.745987
----------------------------------------------------------------
Test results for Abs Rel : b'3.18921' % +/- b'0.11278' (jitter = b'0.50106')
Test results for Sq Rel : b'193.020' % +/- b'8.26548' (jitter = b'37.4728')
Test results for RMSE : b'43.8260' % +/- b'0.89049' (jitter = b'2.44292')
Test results for RMSEl : b'1.41643' % +/- b'0.02271' (jitter = b'0.08594')
Test results for a1 : b'0.14217' % +/- b'0.00765' (jitter = b'0.04241')
Test results for a2 : b'0.26711' % +/- b'0.01180' (jitter = b'0.05237')
Test results for a3 : b'0.37170' % +/- b'0.01334' (jitter = b'0.06998')

```

Any ideas why is it going like this?

**Comment by michael-fonder** [comment]
Hi!

First of all, thank you for your interest in our work!

Your issue looks similar to one I encountered when writing the code. My issue was due to a bug in cuda that made the matrix multiplications silently fail randomly and output garbage. This happens only on GPUs and for cuda 10 drivers (10.x).

To overcome this, you have two options; Either you update your cuda driver (and therefore your tensorflow install) or you set the code to perform matrix multiplications on the CPU (you can do this by setting the '--cpu_matmul'  flag when launching the code).

Just for your information, you can monitor the outputs of the network in real time by using tensorboard. You can use it to detect potential issues without having to wait for the end of the complete training process.

Let me know if this solves your issue.

**Comment by dimaxano** [comment]
Hi, michael!

I tried with `--cpu_matmul`, but I'm getting an error with the following traceback

```bash
2021-07-06 20:05:32.272669: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55ca14b82a00,impl=0x55ca14b82790] did not memset GPU location; source: 0x7f7c817fbb00; size: 8388608; pattern: ffffffff
2021-07-06 20:05:32.272678: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55ca14b82a00,impl=0x55ca14b82790] did not memset GPU location; source: 0x7f7c817fbb20; size: 8388608; pattern: ffffffff
2021-07-06 20:05:32.272729: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_ops.cc:1006 : Not found: No algorithm worked!
2021-07-06 20:05:32.272757: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55ca14b82a00,impl=0x55ca14b82790] did not memset GPU location; source: 0x7f7c817fbb00; size: 8388608; pattern: ffffffff
2021-07-06 20:05:32.272766: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55ca14b82a00,impl=0x55ca14b82790] did not memset GPU location; source: 0x7f7c817fbb20; size: 8388608; pattern: ffffffff
2021-07-06 20:05:32.272776: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_ops.cc:1006 : Not found: No algorithm worked!
2021-07-06 20:05:32.272797: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55ca14b82a00,impl=0x55ca14b82790] did not memset GPU location; source: 0x7f7c817fbb00; size: 8388608; pattern: ffffffff
2021-07-06 20:05:32.272806: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55ca14b82a00,impl=0x55ca14b82790] did not memset GPU location; source: 0x7f7c817fbb20; size: 8388608; pattern: ffffffff
2021-07-06 20:05:32.272819: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_ops.cc:1006 : Not found: No algorithm worked!
2021-07-06 20:05:32.272840: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55ca14b82a00,impl=0x55ca14b82790] did not memset GPU location; source: 0x7f7c817fbb00; size: 8388608; pattern: ffffffff
2021-07-06 20:05:32.272845: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55ca14b82a00,impl=0x55ca14b82790] did not memset GPU location; source: 0x7f7c817fbb20; size: 8388608; pattern: ffffffff
2021-07-06 20:05:32.272857: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_ops.cc:1006 : Not found: No algorithm worked!
2021-07-06 20:05:32.272877: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55ca14b82a00,impl=0x55ca14b82790] did not memset GPU location; source: 0x7f7c817fbb00; size: 8388608; pattern: ffffffff
2021-07-06 20:05:32.272884: I tensorflow/stream_executor/stream.cc:4976] [stream=0x55ca14b82a00,impl=0x55ca14b82790] did not memset GPU location; source: 0x7f7c817fbb20; size: 8388608; pattern: ffffffff
2021-07-06 20:05:32.272893: W tensorflow/core/framework/op_kernel.cc:1651] OP_REQUIRES failed at conv_ops.cc:1006 : Not found: No algorithm worked!
STEP: 0STEP: exportTraceback (most recent call last):
  File "/home/dikey/anaconda3/envs/m4depth15/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/home/dikey/anaconda3/envs/m4depth15/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/home/dikey/anaconda3/envs/m4depth15/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: 2 root error(s) found.
  (0) Internal: Blas xGEMMBatched launch failed : a.shape=[3,3,3], b.shape=[3,3,4], m=3, n=4, k=3, batch_size=3
	 [[{{node GPU_0/tower_0/M4Depth_1/upscaler/RIDEN_5/preprocessor/reproject/MatMul}}]]
	 [[GPU_0/tower_0/truediv_5/_774]]
  (1) Internal: Blas xGEMMBatched launch failed : a.shape=[3,3,3], b.shape=[3,3,4], m=3, n=4, k=3, batch_size=3
	 [[{{node GPU_0/tower_0/M4Depth_1/upscaler/RIDEN_5/preprocessor/reproject/MatMul}}]]
0 successful operations.
0 derived errors ignored.
```

Also I tried to install tf == 1.12 with cuda 9 to eliminate that error. After some syntax modification, code still failing [here](https://github.com/michael-fonder/M4Depth/blob/4d09d4a12e162bf0bf64c5d9b677455b9bb21bcd/m4depth_model.py#L116)
with error 
`tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimension 1 in both shapes must be equal, but are 1 and 6. Shapes are [3,1,1] and [3,6,6]. for 'GPU_0/tower_0/M4Depth_1/upscaler/RIDEN_5/preprocessor/reproject/MatMul_1' (op: 'BatchMatMul') with input shapes: [3,1,1,3,4], [3,6,6,4,1].`

Fast research showed that `tf==1.12` uses `BatchMatMul` for `tf.matmul`, but `tf==1.15` uses `BatchMatMulV2`

Maybe you have ideas what to try next?

BTW, I am running evaluation only with the weights provided with this repo

**Comment by michael-fonder** [comment]
Hi Dmitry,

I've never seen your Blas error before. A quick search hinted that it's probably due to a tensorflow setup issue on your computer rather than an error in the code.

For your tensorflow error, I guess that they changed the broadcast rules between 1.12 and 1.15. The following code modification should do the trick:
```
with tf.device(self.MATMUL_DEVICE):
        proj_pos = tf.linalg.matmul( tf.tile(combined_mat, [1,h,w,1] ), pos_vec)
```

If this solves your issue, I'll push the change to the master branch for other users.

**Comment by dimaxano** [comment]
Hi Michael,

Adding `tile` function with arguments `[1, h, w, 1, 1]` (differs a bit from yours) where you pointed and also [here](https://github.com/michael-fonder/M4Depth/blob/4d09d4a12e162bf0bf64c5d9b677455b9bb21bcd/m4depth_model.py#L80) makes code not fail at the graph initialization stage, but (with `--cpu_matmul`, GPU version failed with `Blas xGEMMBatched launch failed`) it is still producing grey-only depth maps (`tf==1.12`, `cuda==9`)

I think the thing that I'm on 3070 GPU may play its negative role. I will try tf2.5 which support CUDA 11 (not many modifications should be applied, I think)

**Comment by michael-fonder** [comment]
Indeed, I've read plenty of threads mentionning incompatibilites between RTX 30xx GPUs and cuda drivers older than version 11.1...

If you're interested, NVidia provides docker files for various machine learning libraries. I'm using them on a day to day basis. They have one for tf v1.15 built against the latest cuda drivers. It should therefore work for your GPU. If you don't use docker, I've found [this guide](https://www.pugetsystems.com/labs/hpc/How-To-Install-TensorFlow-1-15-for-NVIDIA-RTX30-GPUs-without-docker-or-CUDA-install-2005/) that explains of to use their custom builds within a conda environment.

I'm not familiar with tensorflow 2 unfortunately. I won't be able to help much for making the code compatible with tf2. 

> Adding tile function with arguments [1, h, w, 1, 1] (differs a bit from yours)

You're correct about the modification. Sorry for the mistake.

**Comment by dimaxano** [comment]
I tried to run on 2080Ti GPUs and it works correctly! Just out of the box
Even without `--cpu_matmul` (btw, please, check [that](https://github.com/michael-fonder/M4Depth/blob/4d09d4a12e162bf0bf64c5d9b677455b9bb21bcd/m4depth_model.py#L24) code: if we choose `cpu_matmul` device should be `cpu`, not `gpu`, isn't it? I corrected it locally for myself)


@michael-fonder thank you for help with that problem!
